# -*- coding: utf-8 -*-
"""model SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tSeb06S9VCJ6cRzRjnRxbn4aAnd5blW

SVM model : การคัดเลือกคุณลักษณะที่เหมาะสมสำหรับการพยากรณ์การเลื่อนตำแหน่ง.
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC  # ใช้ SVC แทน SVM
from sklearn.metrics import classification_report, accuracy_score

data = pd.read_csv("Employee_Clean.csv") #โหลดข้อมูล

data.head()

#แบ่งข้อมูลเป็น train, test
X = data.drop("is_promoted", axis=1)
y = data["is_promoted"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

#แปลง department
X_train = pd.get_dummies(X_train, columns=['department'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['department'], drop_first=True)

X_train

#แปลง education เป็นตัวเลข
education_mapping = {
    "Master's & above": 3,
    "Bachelor's": 2,
    "Below Secondary": 1
    }
X_train['education'] = X_train['education'].map(education_mapping)
X_test['education'] = X_test['education'].map(education_mapping)
#แปลง gender เป็น ตัวเลข
gender_mapping = {
    "Male": 0,
    "Female": 1
    }
X_train['gender'] = X_train['gender'].map(gender_mapping)
X_test['gender'] = X_test['gender'].map(gender_mapping)

# ทำการมาตรฐานข้อมูล Standardization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

svm_model = SVC(kernel='linear', C=1.0)  # ในกรณีนี้เราใช้ kernel เป็นเส้นตรง (linear)
# train model
svm_model.fit(X_train, y_train)
# test model
y_pred = svm_model.predict(X_test)

# ประเมินผลโมเดล
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))