# -*- coding: utf-8 -*-
"""RandomForest model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MChVV3Wx4F4O69uvvvdCOkmzCHUFINsL
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

data = pd.read_csv("Employee_Clean.csv")

data.head()

# การเตรียมข้อมูล: แปลงตัวแปรแบบอักษรเป็นตัวเลข
data = pd.get_dummies(data, columns=["department",  "education", "gender"])

# เป้าหมาน
X = data.drop("is_promoted", axis=1)
y = data["is_promoted"]

# แบ่งชุดข้อมูลเป็นชุดฝึกและชุดทดสอบ
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# สร้างโมเดล Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42) #โมเดล Random Forest ใช้ 100 ต้นไม้ในการพยากรณ์การเลื่อนตำแหน่ง (is_promoted)
# ฝึก
rf_model.fit(X_train, y_train)
# ทดสอบ
y_pred = rf_model.predict(X_test)

# ประเมิน
accuracy = accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(f"Accuracy: {accuracy}")